/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.jtam2000.package1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SampleAvroRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4650495230223037826L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SampleAvroRecord\",\"namespace\":\"com.github.jtam2000.package1\",\"fields\":[{\"name\":\"IntegerValue\",\"type\":\"int\",\"doc\":\"an integer value\"},{\"name\":\"StringValue\",\"type\":[\"null\",\"string\"],\"doc\":\"string value\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SampleAvroRecord> ENCODER =
      new BinaryMessageEncoder<SampleAvroRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SampleAvroRecord> DECODER =
      new BinaryMessageDecoder<SampleAvroRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SampleAvroRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SampleAvroRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SampleAvroRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SampleAvroRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SampleAvroRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SampleAvroRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SampleAvroRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SampleAvroRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** an integer value */
   private int IntegerValue;
  /** string value */
   private java.lang.CharSequence StringValue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SampleAvroRecord() {}

  /**
   * All-args constructor.
   * @param IntegerValue an integer value
   * @param StringValue string value
   */
  public SampleAvroRecord(java.lang.Integer IntegerValue, java.lang.CharSequence StringValue) {
    this.IntegerValue = IntegerValue;
    this.StringValue = StringValue;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return IntegerValue;
    case 1: return StringValue;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: IntegerValue = (java.lang.Integer)value$; break;
    case 1: StringValue = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'IntegerValue' field.
   * @return an integer value
   */
  public int getIntegerValue() {
    return IntegerValue;
  }


  /**
   * Sets the value of the 'IntegerValue' field.
   * an integer value
   * @param value the value to set.
   */
  public void setIntegerValue(int value) {
    this.IntegerValue = value;
  }

  /**
   * Gets the value of the 'StringValue' field.
   * @return string value
   */
  public java.lang.CharSequence getStringValue() {
    return StringValue;
  }


  /**
   * Sets the value of the 'StringValue' field.
   * string value
   * @param value the value to set.
   */
  public void setStringValue(java.lang.CharSequence value) {
    this.StringValue = value;
  }

  /**
   * Creates a new SampleAvroRecord RecordBuilder.
   * @return A new SampleAvroRecord RecordBuilder
   */
  public static com.github.jtam2000.package1.SampleAvroRecord.Builder newBuilder() {
    return new com.github.jtam2000.package1.SampleAvroRecord.Builder();
  }

  /**
   * Creates a new SampleAvroRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SampleAvroRecord RecordBuilder
   */
  public static com.github.jtam2000.package1.SampleAvroRecord.Builder newBuilder(com.github.jtam2000.package1.SampleAvroRecord.Builder other) {
    if (other == null) {
      return new com.github.jtam2000.package1.SampleAvroRecord.Builder();
    } else {
      return new com.github.jtam2000.package1.SampleAvroRecord.Builder(other);
    }
  }

  /**
   * Creates a new SampleAvroRecord RecordBuilder by copying an existing SampleAvroRecord instance.
   * @param other The existing instance to copy.
   * @return A new SampleAvroRecord RecordBuilder
   */
  public static com.github.jtam2000.package1.SampleAvroRecord.Builder newBuilder(com.github.jtam2000.package1.SampleAvroRecord other) {
    if (other == null) {
      return new com.github.jtam2000.package1.SampleAvroRecord.Builder();
    } else {
      return new com.github.jtam2000.package1.SampleAvroRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for SampleAvroRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SampleAvroRecord>
    implements org.apache.avro.data.RecordBuilder<SampleAvroRecord> {

    /** an integer value */
    private int IntegerValue;
    /** string value */
    private java.lang.CharSequence StringValue;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.jtam2000.package1.SampleAvroRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.IntegerValue)) {
        this.IntegerValue = data().deepCopy(fields()[0].schema(), other.IntegerValue);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.StringValue)) {
        this.StringValue = data().deepCopy(fields()[1].schema(), other.StringValue);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing SampleAvroRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.jtam2000.package1.SampleAvroRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.IntegerValue)) {
        this.IntegerValue = data().deepCopy(fields()[0].schema(), other.IntegerValue);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.StringValue)) {
        this.StringValue = data().deepCopy(fields()[1].schema(), other.StringValue);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'IntegerValue' field.
      * an integer value
      * @return The value.
      */
    public int getIntegerValue() {
      return IntegerValue;
    }


    /**
      * Sets the value of the 'IntegerValue' field.
      * an integer value
      * @param value The value of 'IntegerValue'.
      * @return This builder.
      */
    public com.github.jtam2000.package1.SampleAvroRecord.Builder setIntegerValue(int value) {
      validate(fields()[0], value);
      this.IntegerValue = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'IntegerValue' field has been set.
      * an integer value
      * @return True if the 'IntegerValue' field has been set, false otherwise.
      */
    public boolean hasIntegerValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'IntegerValue' field.
      * an integer value
      * @return This builder.
      */
    public com.github.jtam2000.package1.SampleAvroRecord.Builder clearIntegerValue() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'StringValue' field.
      * string value
      * @return The value.
      */
    public java.lang.CharSequence getStringValue() {
      return StringValue;
    }


    /**
      * Sets the value of the 'StringValue' field.
      * string value
      * @param value The value of 'StringValue'.
      * @return This builder.
      */
    public com.github.jtam2000.package1.SampleAvroRecord.Builder setStringValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.StringValue = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'StringValue' field has been set.
      * string value
      * @return True if the 'StringValue' field has been set, false otherwise.
      */
    public boolean hasStringValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'StringValue' field.
      * string value
      * @return This builder.
      */
    public com.github.jtam2000.package1.SampleAvroRecord.Builder clearStringValue() {
      StringValue = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SampleAvroRecord build() {
      try {
        SampleAvroRecord record = new SampleAvroRecord();
        record.IntegerValue = fieldSetFlags()[0] ? this.IntegerValue : (java.lang.Integer) defaultValue(fields()[0]);
        record.StringValue = fieldSetFlags()[1] ? this.StringValue : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SampleAvroRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<SampleAvroRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SampleAvroRecord>
    READER$ = (org.apache.avro.io.DatumReader<SampleAvroRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.IntegerValue);

    if (this.StringValue == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.StringValue);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.IntegerValue = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.StringValue = null;
      } else {
        this.StringValue = in.readString(this.StringValue instanceof Utf8 ? (Utf8)this.StringValue : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.IntegerValue = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.StringValue = null;
          } else {
            this.StringValue = in.readString(this.StringValue instanceof Utf8 ? (Utf8)this.StringValue : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










